// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFileConnections(arg1:string):Promise<Array<main.FileConnection>>;

export function Greet(arg1:string):Promise<string>;

export function ScanRepository(arg1:string):Promise<main.FileInfo>;

export function SelectDirectory():Promise<string>;
